name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore WorkShop.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal WorkShop.sln
    - name: Publish
      run: dotnet publish WorkShop.sln
    - name: Generate ZIP
      uses: byteever/action-build-zip@master
      with:
         filename: 'release.zip'
    - uses: mkrakowitzer/actions-googledrive@master
      with:
        upload-from: ./tmp
        upload-to: IRL-L2-Support/platform-architecture-docs
        skicka-tokencache-json: ${{ secrets.FOO }}
        google-client-id: ${{ secrets.BAR }}
        google-client-secret: ${{ secrets.BAZ }}
