name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Upload files to Google Drive
      uses: mkrakowitzer/actions-googledrive@1
    - name: action-build-zip
      uses: byteever/action-build-zip@1

    - name: Restore dependencies
      run: dotnet restore WorkShop.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal WorkShop.sln
    - name: Publish
      run: dotnet publish WorkShop.sln
