name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore WorkShop.sln
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal WorkShop.sln
    - name: Publish
      run: dotnet publish WorkShop.sln
    
    - name: action-zip
      uses: montudor/action-zip@v1.0.0
    - uses: montudor/action-zip@v1
      with:
         args: zip -qq -r dir.zip dir
    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -qq -r function.zip dist node_modules package.json
      working-directory: path/to/work-dir
      

    
